# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (C) 2026 James Augustus
"""Content hashes of Radiance inputs and an immutable cache of completed builds."""
from collections import OrderedDict
import hashlib
import json
import os
import threading

from core.file_safety import internal_path

_digests = OrderedDict()
_commands = OrderedDict()
_lock = threading.RLock()
build_lock = threading.RLock()


def file_digest(path):
    """Content SHA-256, reused within the process when stat information is unchanged.

    Track ctime, mtime, inode and size together. A hash produced while the source
    changes is not cached. The next call reads the file from the beginning.
    """
    path = os.path.abspath(path)
    st = os.stat(path)
    key = (path, st.st_dev, st.st_ino, st.st_size, st.st_mtime_ns, st.st_ctime_ns)
    with _lock:
        if key in _digests:
            _digests.move_to_end(key)
            return _digests[key]
    with open(path, 'rb') as f:
        h = hashlib.file_digest(f, 'sha256').hexdigest() if hasattr(hashlib, 'file_digest') else _stream_digest(f)
    suffix = os.stat(path)
    if (st.st_ino, st.st_size, st.st_mtime_ns, st.st_ctime_ns) != (suffix.st_ino, suffix.st_size, suffix.st_mtime_ns, suffix.st_ctime_ns):
        raise RuntimeError('Render input changed while being read: ' + os.path.basename(path))
    with _lock:
        _digests[key] = h
        while len(_digests) > 4096:
            _digests.popitem(last=False)
    return h


def _stream_digest(f):
    h = hashlib.sha256()
    for b in iter(lambda: f.read(1 << 20), b''):
        h.update(b)
    return h.hexdigest()


def object_digest(data):
    return hashlib.sha256(json.dumps(data, sort_keys=True, ensure_ascii=False,
                                     allow_nan=False, separators=(',', ':')).encode()).hexdigest()


def has_dynamic_rad(sources):
    """All dependencies of shell commands in a user's RAD file cannot be determined.

    These scenes are rebuilt each time. The deterministic xform/gensky lines
    generated by this program are outside this list. Their inputs
    are tracked separately.
    """
    for path, digest in sources:
        if not path.lower().endswith('.rad'):
            continue
        key = (path, digest)
        with _lock:
            known = key in _commands
            present = _commands.get(key)
        if not known:
            with open(path, 'rb') as f:
                # Radiance also runs ! mid-line. Any ! byte counts as dynamic.
                present = any(b'!' in chunk for chunk in iter(lambda: f.read(1 << 20), b''))
            with _lock:
                _commands[key] = present
                while len(_commands) > 4096:
                    _commands.popitem(last=False)
        if present:
            return True
    return False


def sources(project_dir, project, library=None):
    """Project inputs and photometry/texture sidecar files, excluding render outputs.

    A slightly broader scope avoids reusing a stale lighting calculation due to
    a missing dependency. Backup/output and octree directories are not scanned.
    """
    paths = set()
    for lower in ('model', 'material', 'light', 'texture', 'sky', '_cache/ies', '_cache/texture'):
        directory = internal_path(project_dir, lower)
        if os.path.isdir(directory):
            for root, directories, names in os.walk(directory, followlinks=False):
                directories[:] = sorted(d for d in directories if not os.path.islink(os.path.join(root, d)))
                for name in names:
                    p = os.path.join(root, name)
                    if not name.endswith(('.tmp', '.new')) and os.path.isfile(p):
                        # Links outside the project are not accepted as inputs.
                        p = internal_path(project_dir, os.path.relpath(p, project_dir))
                        paths.add(p)
    for g in project.get('geometry', []):
        p = internal_path(project_dir, g['file'])
        if os.path.isfile(p):
            paths.add(p)
        if os.path.isfile(p + '.full.obj'):
            paths.add(p + '.full.obj')
    for rel in project.get('lights', []):
        p = internal_path(project_dir, rel)
        if os.path.isfile(p):
            paths.add(p)
    mat = internal_path(project_dir, project.get('material', 'material/materials.rad'))
    if os.path.isfile(mat):
        paths.add(mat)
    for a in project.get('luminaires', []):
        for field in ('ies', 'product_rad'):
            rel = a.get(field)
            if not rel:
                continue
            try:
                p = internal_path(project_dir, rel)
            except ValueError:
                continue
            if os.path.isfile(p):
                paths.add(p)
                # Also track changes to .dat/.cal files alongside the product .rad file.
                if field == 'product_rad':
                    for extension in ('.dat', '.cal'):
                        sidecar = os.path.splitext(p)[0] + extension
                        if os.path.isfile(sidecar):
                            paths.add(sidecar)
            elif library and field == 'ies':
                from core.photometry import ies_source
                p = ies_source(project_dir, a, library)
                if p:
                    paths.add(p)
    return [(os.path.abspath(p), file_digest(p)) for p in sorted(paths)]


def valid_output(path, record_path):
    """Reuse only output with a recorded successful build and a valid size."""
    try:
        with open(record_path) as f:
            record = json.load(f)
        return (os.path.getsize(path) > 64 and record['sha256'] == file_digest(path))
    except (OSError, ValueError, KeyError, TypeError):
        return False


def valid_scene(project_dir, oct_path, record_path):
    """Validate the scene together with the derived geometry it references."""
    try:
        if not valid_output(oct_path, record_path):
            return False
        with open(record_path) as f:
            dependencies = json.load(f)['derived']
        if not isinstance(dependencies, list):
            return False
        for record in dependencies:
            if not isinstance(record, dict) or not isinstance(record.get('path'), str) or not isinstance(record.get('sha256'), str):
                return False
            path = internal_path(project_dir, record['path'])
            if not os.path.isfile(path) or file_digest(path) != record['sha256']:
                return False
        return True
    except (OSError, ValueError, KeyError, TypeError, RuntimeError):
        return False
